# Copyright (C) 2022 Shra1V32 <namanageshwar@outlook.com>
name: Tata Sky Daily Workflow
on:
 schedule:
   - cron: "00 21  * * *"
 workflow_dispatch:
  inputs:
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Daily Loop
      run: |
            git config --global user.name "PROXBOY"
            git config --global user.email "75972578+PROXBOY@users.noreply.github.com"
            git clone https://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@github.com/PROXBOY/TataSkyIPTV-Daily
            cd TataSkyIPTV-Daily/
            cd code_samples/
            curl -s 'https://raw.githubusercontent.com/ForceGT/Tata-Sky-IPTV/master/code_samples/allChannels.json' > allChannels.json
            chmod 755 *
            python3 utils.py 
            git clone https://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@gist.github.com/331f141beaed615e19510bedb22260bf
            rm 331f141beaed615e19510bedb22260bf/allChannelPlaylist.m3u
            mv *.m3u 331f141beaed615e19510bedb22260bf/
            cd 331f141beaed615e19510bedb22260bf
            git add .
            git commit --amend -m "Playlist has been updated."
            git push -f
